### PR TITLE
fix #48 (mw.set drops property names with numbers in key-value mode)

### LINKED ISSUE #48: mw.set drops property names with numbers in key-value mode
### Setup and configuration

- SMW version: 2.2.5
- SSC version: 1.0.0
- MW version: 1.30.0
- DB (MySQL etc.): MySQL

### Issue

When setting properties by using key-value form, if the "key" part contains numbers, then the property will not be accepted (more like simply get ignored).

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):
Using following table to setup properties. ([source](https://sandbox.semantic-mediawiki.org/wiki/Module:SmwLuaTest))
```
local settings = {
	['hello'] = 'world',
	['hell0'] = 'world',
	'HELLO=WORLD',
	'HELL0=WORLD',
}
```
Only ```['hell0'] = 'world'```  doesn't show up on [browse page](https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Honestleaf/SmwLuaTest).

### PR DESCRIPTION
**Pull request by oetterer**
adds:
- a test, including fixture, to reproduce the problem
- a fix for the problem (regular expressions and I are still at odds, it seems)

closes #48

### CODE REVIEW

**Comment by oetterer** [comment]
hm. Can I be so bold and assume, that the failing master test is not caused by my fix...

**Comment by mwjames** [comment]
> hm. Can I be so bold and assume, that the failing master test is not caused
> by my fix..

Yes, and most likely caused by [0].

PS: [1] shows how to deal with different MW releases where the output changed.

[0] https://github.com/wikimedia/mediawiki/commit/3bae295aef6f6495dc37802f1f4f6956c9a5648c
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/24ef304aa31a2cd20123bf5e40b1a178dd7d5f31/tests/phpunit/Integration/JSONScript/TestCases/s-0014.json#L70-L112

Cheers

**Comment by oetterer** [comment]
thank you @mwjames, that helps. Will fix the tests tomorrow!

**Comment by oetterer** [comment]
@mwjames you could have mentioned, that I had to patch \SMW\Scribunto\Integration\JSONScript\SemanticScribuntoJsonTestCaseScriptRunnerTest first to use this feature! ;)
All ready now. I took the liberty to merge the test patches, but normally I would let you (or @kghbln) do the honors.

**Comment by mwjames** [comment]
> @mwjames you could have mentioned, that I had to patch 

Sorry this slipped my mind.

I thought I'd give you an early feedback so that you can work your way through without me having to intervene during the weekend.

**Comment by mwjames** [comment]
> Should I do a 1.1.1 next week?

If you have time then that would be splendid.

**Pull request merged**
