### PR TITLE
Make 2.1.0 release

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #68 

This PR addresses or contains:
- Updated release notes
- Updated readme
- Updated meta files

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

Fixes #

### CODE REVIEW

**Comment by mwjames** [comment]
I find the installation instruction rather lengthy.

**Comment by mwjames** [comment]
The essence is add composer.local and wfLoadExtension, the rest is just prose and can be put into amendments otherwise it looks rather complicated.

**Comment by kghbln** [comment]
> I find the installation instruction rather lengthy.

I is bigger in size it uses in the document but it is actually stuff than before. Anyways most other installation requirements look like this now and these really guide you trough the process increasing admin confidence. :)

**Comment by kghbln** [comment]
> The essence is add composer.local and wfLoadExtension, the rest is just prose and can be put into amendments otherwise it looks rather complicated.

We could think of removing the composer installation information in future, but in the end it increases guidance.

**Comment by mwjames** [comment]
> We could think of removing the composer installation information in future, but in the end it increases guidance.

Sorry, I killed some of the verbosity so that the instructions can be viewed on one page without scrolling.

**Comment by kghbln** [comment]
I personally rather have consistency than this mess across the repos we currently have. Will change the other extensions accordingly.

**Pull request merged**
