### PR TITLE
Adding mw.smw.set to available smw functions

### PR DESCRIPTION
**Pull request by oetterer**

### CODE REVIEW

**Comment by oetterer** [comment]
I added the smw parser function "set" to the available lua functions.

The implementation re-uses as much code as possible from the smw parser function call. It utilizes class _ParserFunctionFactory_ to get the same kind of object, the normal parser function call would use. It then defers parameter processing and the semantic storage process to this object the same way a normal parser function call would use.

Difference to the parser function call is:
- it does a preliminary argument processing to catch multiple formats
- it aborts on empty parameters
- it returns _true_ on success and an array containing the error message in case of failure/warnings

**Comment by oetterer** [comment]
btw: I'm going to write documentation for all new functions in https://github.com/SemanticMediaWiki/SemanticScribunto/blob/master/docs/functions.md once the code is integrated. promise!

**Comment by mwjames** [comment]
... now on my weekly support slot ...

> btw: I'm going to write documentation for all new functions in https://github.com/SemanticMediaWiki/SemanticScribunto/blob/master/docs/functions.md once the code is integrated. promise!

You don't have to promise, it would be a shame if people cannot make use of your effort just because of some missing guidelines.

PS: After all the PR's have been merged, don't forget to put yourself as author to this extension given the expected amount of contribution.

**Comment by mwjames** [comment]
There are some design issues but some have already being addressed in #20 therefore merging this so we can move forward.

**Comment by JeroenDeDauw** [comment]
Now the one with the improved code has a merge conflict with master...

**Pull request merged**
