### PR TITLE
Start 1.2.0

### PR DESCRIPTION
**Pull request by kghbln**

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames I have no idea what is going on. The errors should not appear I believe. :|

**Comment by oetterer** [comment]
@kghbln looks like travis installs the wrong smw version:
```bash
 731 - Installing mediawiki/semantic-media-wiki (2.5.x-dev e0c6791): Cloning e0c679168a from cache
```
should be 3.0-dev somthing

If I had to venture a guess this entry in composer.json's require-dev:
```
"mediawiki/semantic-media-wiki": "@dev"
```
picks the latest dev commit? maybe try and change to "~3.0@dev"?

**Comment by kghbln** [comment]
This commit is restoring the status ante so it should install 3.0. Probably just a matter of merging to make the issue go away. This is a bit exhausting but probably the way it is.

**Comment by oetterer** [comment]
nope. I'll leave you to it. Sorry, that I couldn't be of any help. :(

**Comment by mwjames** [comment]
> nope. I'll leave you to it. Sorry, that I couldn't be of any help. :(

Please remember that composer requirements are registered with
packagist.org which currently has only ~2.5 as constraint. This RR
changes those requirements only __after__ it has been merged therefore
it is natural that test fail hat require 3.0. The tasks is as to add
~2.5|~3.0 and merge the PR.

Cheers

**Comment by kghbln** [comment]
I guess another senior moments case for me. I think to remember that I forget this all the time. :( Thanks for getting this off the ground.

**Comment by kghbln** [comment]
Yeah, we are in fluff again.

**Pull request merged**
