### PR TITLE
add feature #55: set and subobject can take property values from subtables

### LINKED ISSUE #55: mw.smw.set should recognize multiple values for one property given in a sub-table
### Setup and configuration

- SMW version: 2.5.6
- SSC version: 1.1.1
- MW version: 1.30
- DB (MySQL etc.): 10.0.34-MariaDB

### Issue

`mw.smw.set()` allows setting multiple values for the same property by having arguments like
```
table#1 { 
  "prop=value", 
  "prop=value2", 
}
```

It would be great if it could handle arguments of the form
```
table#1 { 
  ["prop"] = table#2 { 
    "value",
    "value2", 
  }, 
}
```

(This is also the format returned by `mw.smw.ask()` when the result has multiple values for one property.)

### PR DESCRIPTION
**Pull request by oetterer**
Fixes #55

### CODE REVIEW

**Comment by oetterer** [comment]
Looks to me, the failing test originates in smw, not ssc. see also [0].

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/402183163

**Comment by mwjames** [comment]
> Looks to me, the failing test originates in smw, not ssc. see also [0].
>
> [0]
> https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/402183163

A quick look reveals that it is caused by MW and the MCR.

PS: Being absent for two month means that things are getting worse for
extension developers by the month. I'll try to have look at it during
my weekend sprint.

```
Fatal error: Uncaught exception 'MWException' with message
'RevisionStore for its_a_mw cannot be used with a DB connection for
its_a_mw-sunittest_' in
/home/travis/build/SemanticMediaWiki/mw/includes/Storage/RevisionStore.php:1983
Stack trace:
#0 /home/travis/build/SemanticMediaWiki/mw/includes/Storage/RevisionStore.php(406):
MediaWiki\Storage\RevisionStore->checkDatabaseWikiId()
#1 /home/travis/build/SemanticMediaWiki/mw/includes/Storage/PageUpdater.php(1093):
MediaWiki\Storage\RevisionStore->insertRevisionOn()
#2 /home/travis/build/SemanticMediaWiki/mw/includes/Storage/PageUpdater.php(731):
MediaWiki\Storage\PageUpdater->doCreate()
#3 /home/travis/build/SemanticMediaWiki/mw/includes/page/WikiPage.php(1855):
MediaWiki\Storage\PageUpdater->saveRevision()
#4 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/PageCreator.php(93):
WikiPage->doEditContent()
#5 /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/PageCreator.php(71):
SMW\Tests\Utils\PageCreator->doEdit()
```
Cheers

**Comment by mwjames** [comment]
@oetterer Thanks for the test coverage and the quick response to the request.

Tests on master were the only one that failed due to extraneous reasons and should be resolved by now. I'll leave the release to both of you @kghbln @oetterer.

**Comment by s7eph4n** [comment]
Thanks, @oetterer !
And welcome back, @mwjames !

**Comment by oetterer** [comment]
@mwjames I hope you had a relaxing vacation in the last two month! Or at least a good time! :)

about the tests: wouldn't it be better to mark the test on master as _allow_failures_. Also, shouldn't we chnage the test on 1.28 to 1.31?

**Comment by kghbln** [comment]
I will do a 1.2.0 release probably on Wednesday if there are no objections from anyone of you.

**Pull request merged**
