### PR TITLE
Adding mw.smw.ask to available smw functions

### PR DESCRIPTION
**Pull request by oetterer**
In reference to #11 I added 'ask' to the available lua functions. This PR also includes a section in the documentation about the differences between the ask and getQueryResult.

### CODE REVIEW

**Comment by mwjames** [comment]
Requires a rebase after #23 has been merged.

**Comment by mwjames** [comment]
Probably a matter of personal style but when creating a large `dataProvider`, I would go for individual providers because in case the test fails you would need to count/find the array entry and change the structure which may prove difficult in some situations.

```
$provider['Can explain the purpose'] = [

];

// or leave it and be assigned a number
$provider[] = [

];

return $provider;

```

Nothing that prevents it from merging.

**Comment by mwjames** [comment]
What happens when you use `format=debug` with the ask parameters? `format=debug` doesn't return a `QueryResult` object (returns a string).

**Comment by oetterer** [comment]
> Probably a matter of personal style but when creating a large dataProvider, I would go for individual providers because in case the test fails you would need to count/find the array entry and change the structure which may prove difficult in some situations.

Thanks for the suggestion. Was looking for a way to annotate tests. Will work this in, next time I touch the tests.

> What happens when you use format=debug with the ask parameters? format=debug doesn't return a QueryResult object (returns a string).

Thank you very much for pointing this out. Did not know that. Put a  PR (#26) online with a suggestion to handle this.

**Comment by mwjames** [comment]
> Thank you very much for pointing this out. Did not know that. Put a PR (#26) online with a suggestion to handle this.

I guessed that much hence my inquiry.

**Pull request merged**
